"""add FK and and relationship to products in cart_items

Revision ID: 4b8621c505a0
Revises: 955c81d7bdc7
Create Date: 2026-04-06 02:22:48.904562

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b8621c505a0"
down_revision: Union[str, None] = "955c81d7bdc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "cart_items", "products", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cart_items", type_="foreignkey")
    # ### end Alembic commands ###
