"""add rich product fields

Revision ID: 4fd413fc07c0
Revises: 7c482acda521
Create Date: 2026-04-23 18:27:33.489069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd413fc07c0'
down_revision: Union[str, None] = '7c482acda521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('stock_status', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('tags_json', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('flavors_json', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('sizes_json', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('features', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('ingredients', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('nutrition_facts', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('usage_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'usage_info')
    op.drop_column('products', 'nutrition_facts')
    op.drop_column('products', 'ingredients')
    op.drop_column('products', 'features')
    op.drop_column('products', 'sizes_json')
    op.drop_column('products', 'flavors_json')
    op.drop_column('products', 'tags_json')
    op.drop_column('products', 'images')
    op.drop_column('products', 'is_new')
    op.drop_column('products', 'stock_status')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'original_price')
    # ### end Alembic commands ###