"""add refund requests table

Revision ID: 713595850f32
Revises: 7955acb687a7
Create Date: 2026-05-02 15:47:01.383041

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "713595850f32"
down_revision: Union[str, None] = "7955acb687a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refund_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("order_item_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("refund_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_item_id"],
            ["order_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refund_requests_order_id"),
        "refund_requests",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refund_requests_order_item_id"),
        "refund_requests",
        ["order_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_refund_requests_order_item_id"), table_name="refund_requests"
    )
    op.drop_index(op.f("ix_refund_requests_order_id"), table_name="refund_requests")
    op.drop_table("refund_requests")
    # ### end Alembic commands ###
