"""rename total_price to total and unit_price to price in orders

Revision ID: 955c81d7bdc7
Revises: e6ab4dc5d22f
Create Date: 2026-04-06 01:36:43.141594

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '955c81d7bdc7'
down_revision: Union[str, None] = 'e6ab4dc5d22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.alter_column('orders', 'total_price', new_column_name='total')
    op.alter_column('order_items', 'unit_price', new_column_name='price')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.alter_column('orders', 'total', new_column_name='total_price')
    op.alter_column('order_items', 'price', new_column_name='unit_price')