"""make tax_id and address nullable

Revision ID: b0ea58b542b6
Revises: 201d3ed16cc1
Create Date: 2026-03-27 17:57:28.010900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ea58b542b6'
down_revision: Union[str, None] = '201d3ed16cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tax_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'tax_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###