"""add variant_name to order_items

Revision ID: e77703bdd591
Revises: e2e260754b17
Create Date: 2026-05-02 22:33:00.378064

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e77703bdd591"
down_revision: Union[str, None] = "e2e260754b17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items", sa.Column("variant_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "variant_name")
    # ### end Alembic commands ###
